server:
  port: 10889
spring:
  application:
    name: gc-mycat
  datasource:
    name: develop
    url: jdbc:mysql://127.0.0.1:8066/dbtest?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC
#    url: jdbc:mysql://127.0.0.1:3306/dbo1?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: rootroot
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  #spring.datasource.filters = stat,wall,log4j2
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    removeAbandoned: true
    removeAbandonedTimeout: 1800


mybatis:
  mapper-locations: classpath*:mapper/*.xml
