server:
  port: 8080
spring:
  application:
    name: gc-sharding-jdbc
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.allen.sharding.model
sharding:
  jdbc:
    datasource:
      names: ds0
      # 数据源ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://118.31.8.21:3306/krycai
        username: root
        password: rootroot
    config:
      sharding:
        props:
          sql.show: true
        tables:
          t_user:  #t_user表
            key-generator-column-name: id  #主键
            actual-data-nodes: ds0.t_user${0..1}    #数据节点,均匀分布
#            database-strategy: #分库策略
#              inline: #行表达式
#                sharding-column: city_id        #列名称，多个列以逗号分隔
#                algorithm-expression: ds${city_id % 2}    #按模运算分配
            table-strategy:  #分表策略
              inline: #行表达式
                sharding-column: sex
                algorithm-expression: t_user${sex % 2}  #按模运算分配

