server:
  port: 8021
spring:
  #给项目来个名字
  application:
    name: rabbitmq-provider
  #配置rabbitMq 服务器
  rabbitmq:
    host: 1.14.251.70
    port: 30040
    username: weiban
    password: admin123.
    #虚拟host 可以不设置,使用server默认host
#    virtual-host: JCcccHost